version: '2.1'

name: flashcards

services:
  nodejs:
    build:
      context: .
      dockerfile: adonis.dockerfile
    container_name: nodejs_passionlecture
    ports:
      - '3333:3333'
    restart: always
    environment:
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=KKOPY4l340863b43R3E2w6jKxQY-jS2o
      - PORT=3333
      - SESSION_DRIVER=cookie
      - NODE_ENV=production
      - DB_HOST=switchyard.proxy.rlwy.net
      - DB_USER=root
      - DB_PASSWORD=kTyQuNFnrtSAxbNUYMHyWNAIuqlxtTJF
      - DB_DATABASE=railway
      - DB_PORT=53315
    command: /bin/sh -c "node ace migration:run --force && node ./bin/server.js"
