version: '2.1'

name: flashcards

services:
  db:
    image: mysql:8.0.30
    container_name: db_passionlecture
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - '6033:3306'
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_passionlecture
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'

  nodejs:
    build:
      context: .
      dockerfile: adonis.dockerfile
    container_name: nodejs_passionlecture
    ports:
      - '3333:3333'
    restart: always
    environment:
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=KKOPY4l340863b43R3E2w6jKxQY-jS2o
      - PORT=3333
      - SESSION_DRIVER=cookie
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=db
      - DB_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    command: /bin/sh -c "node ace migration:run --force && node ./bin/server.js"

volumes:
  dbdata:
